import { createContext, useState } from 'react';

import { MainNav } from '@/components/MainNav';
import Head from 'next/head';
import WarningModal from './WarningModal';
import { useLeavePageConfirmation } from '@/hooks/useLeavePageConfirmation';



export const Layout = (props) => {
  useLeavePageConfirmation(true)
  return (
      <section>
        <Head>
          <title>Create Next App</title>
          <meta
            name="description"
            content="Generated by create next app"
          />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
          />
          <link
            rel="icon"
            href="/favicon.ico"
          />
        </Head>
        <MainNav />
        <div className="flex justify-center items-center ">{props.children}</div>
        <WarningModal/>
      </section>
  );
};
